### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Natasha998877** [cyberark/White-Phoenix#11]
## Natasha998877User Story

*Using the form below, relate the desired product behavior.  Feel free to
additional, clarifying details below it if needed.  For more details on user
stories, see this [article](https://www.atlassian.com/agile/project-management/user-stories).*

**As a**human
**I want** to stop my ex hacking into all my devices
**So that** I can be left in peace

### Test Scenarios

*If desired, add one or more test scenarios required for user story acceptance.
Ideally, they are executed by automated tests. For more details on Gerkin syntax,
see this [article](https://cucumber.io/docs/gherkin/reference/)*

**Given** this happens every day
**When** always whenever online
**Then** I won't be wasting my life fending him off

### Implementation Tasks

*The following issues have been created to implement this user story:*

* natashaglucina@gmail.com Facebook Natasha Glucina

**Comment by Hechtov** [comment]
Not a repository issue.
You can start by searching "I want to stop my ex hacking into all my devices" in Google or AI bots.
