### ISSUE TITLE
Support for doc and xls files ?

### ISSUE THREAD

**Issue by U4I5** [cyberark/White-Phoenix#3]
#  Input of file encrypted

hello, in the entry of the encrypted file should you put the file extension like:  -f  **file.xlsx.play**  or just  **file.xlsx**?

# Filetype Request

also can you add filetype: doc and xls?

**Comment by novickaa** [comment]
Thanks for sharing your ideas, we are currently investing time and efforts in improving other areas, but we will track your request and add it to our pool of tasks.
